myDict = {'Arsenal': 'ARS',
          'Aston Villa': 'AVL',
          'Brighton and Hove': 'BRI',
          'Burnley': 'BUR',
          'Chelsea': 'CHE',
          'Crystal Palace': 'CRY',
          'Fulham': 'FUL',
          'Leeds United': 'LEE',
          'Leicester City': 'LEI',
          'Liverpool': 'LIV',
          'Manchester City': 'MCI',
          'Manchester United': 'MUN',
          'Newcastle United': 'NEW',
          'Southampton': 'SOU',
          'Sheffield United': 'SHU',
          'Tottenham': 'TOT',
          'West Bromwich': 'WBA',
          'West Ham': 'WHA',
          'Wolverhampton': 'WOL',
          'Everton': 'EVE'}

