myDict = {'Denmark': 'DEN',
          'Scotland': 'SCO',
          'Netherlands': 'NLD',
          'Austria': 'AUS',
          'Russia': 'RUS',
          'Germany': 'GER',
          'Finland': 'FIN',
          'Sweden': 'SWE',
          'Wales': 'WAL',
          'Switzerland': 'SCH',
          'North Macedonia': 'MAK',
          'France': 'FRA',
          'Slovakia': 'SLO',
          'Hungary': 'HUN',
          'England': 'ENG',
          'Poland': 'POL',
          'Turkey': 'TUR',
          'Czech Republic': 'CRE',
          'Italy': 'ITA',
          'Spain': 'SPA',
          'Belgium': 'BEL',
          'Portugal': 'POR',
          'Croatia': 'CRO',
          'Ukraine': 'UKR'}